### ISSUE TITLE
Update Rust to Beta

### ISSUE THREAD

**Issue by maarek** [nsf/pnoise#19]
Update system to use Rust 1.0.0-beta instead of 0.13 for benchmark as this is the most accurate release version up to now.

**Comment by nsf** [comment]
Will do eventually, but it's pointless, because I'm pretty sure rust has the same performance.

**Comment by killercup** [comment]
You're right, the performance probably won't change. For the record, I posted a version that compiles with a recent nightly [on reddit](http://www.reddit.com/r/programming/comments/31mzu1/go_vs_rust_vs_d_vs_crystal_etc_perlin_noise/cq36plt).

**Comment by nsf** [comment]
Rust guys actually maintain that benchmark on their own, you can find the most recent version here: https://github.com/rust-lang/rust/blob/master/src/test/bench/noise.rs

**Comment by killercup** [comment]
Huh, I knew I saw that one before… Don't mind me, then.

**Comment by Vikaton** [comment]
Well Rust is now officially 1.0, so I think it's its appropriate to update?

**Comment by nsf** [comment]
Yeah, will update it soon.
