### ISSUE TITLE
Change README.md to sort the languages

### ISSUE THREAD

**Issue by Ap0ph1s** [nsf/pnoise#21]
D (gdc):            0,066999680 seconds time elapsed
gcc -O3:            0,076729664 seconds time elapsed
Crystal:            0,077063864 seconds time elapsed
Nim (clang):        0,077463342 seconds time elapsed
Rust:               0,078053001 seconds time elapsed
D (ldc2):           0,096995053 seconds time elapsed
clang -O3:          0,143604111 seconds time elapsed
Nim (gcc):          0,159299532 seconds time elapsed
Go gccgo -O3:       0,309625279 seconds time elapsed
D (dmd):            0,339820165 seconds time elapsed
Go gc:              0,360201714 seconds time elapsed
Java:               0,597987438 seconds time elapsed
mono C#:            1,052041381 seconds time elapsed

**Comment by nsf** [comment]
Nope.
