### ISSUE TITLE
Crystal 0.7.1

### ISSUE THREAD

**Issue by Vikaton** [nsf/pnoise#23]
Crystal has updated to 0.7.1 now with non-blocking IO and coroutines

**Comment by asterite** [comment]
@Vikaton Thanks, for pnoise is a pretty simple program, there's no IO nor coroutines involved, so I think upgrading to 0.7.1 won't change anything. It's still worth updating to see if something did change for best or worse, I guess...

**Comment by nsf** [comment]
Will update it soon. I'm waiting for mono update in archlinux repos. :( 4.0 was out with floating point optimization, which is definitely interesting for this benchmark, but archlinux package maintainer seems absent. So, will update it tomorrow maybe, or when new mono arrives to archlinux package repos (I'll update all compilers then).
